### Get All Merchandise
GET http://localhost:3000/api/merchandise
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6InVzZXIxIiwicGFzc3dvcmQiOiIxMjM0NSJ9LCJpYXQiOjE3MDI1MzI4MzEsImV4cCI6MTcwMjUzNjQzMX0.0JNim71QOPP4iMDgo9zqHgnObiL49oJdo8kNc2uItLs
###

### Create New Merchandise
POST http://localhost:3000/api/merchandise
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6InVzZXIxIiwicGFzc3dvcmQiOiIxMjM0NSJ9LCJpYXQiOjE3MDI1MzI4MzEsImV4cCI6MTcwMjUzNjQzMX0.0JNim71QOPP4iMDgo9zqHgnObiL49oJdo8kNc2uItLs


{
    "name": "RandBClothes",
    "price": 20.99
}

###

### Update Merchandise
PUT http://localhost:3000/api/merchandise/20
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6InVzZXIxIiwicGFzc3dvcmQiOiIxMjM0NSJ9LCJpYXQiOjE3MDI1MzI4MzEsImV4cCI6MTcwMjUzNjQzMX0.0JNim71QOPP4iMDgo9zqHgnObiL49oJdo8kNc2uItLs


{
    "name": "waterJet",
    "price": 20.99
}

###

### Delete Merchandise
DELETE http://localhost:3000/api/merchandise/13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJ1c2VybmFtZSI6InVzZXIxIiwicGFzc3dvcmQiOiIxMjM0NSJ9LCJpYXQiOjE3MDI1MzI4MzEsImV4cCI6MTcwMjUzNjQzMX0.0JNim71QOPP4iMDgo9zqHgnObiL49oJdo8kNc2uItLs

### token Merchandise
POST http://localhost:3000/login
Content-Type: application/json


{
  "username": "user1",
  "password": "12345"
}
###